appbase/urls.py
from django.conf.urls import url, include
from django.urls import path
from django.contrib import admin
from . import views
from django.views.static import serve
from django.conf import settings

app_name = 'appbase'

urlpatterns = [
	url(r'^$', views.loginuser, name='login'),
    url(r'^register/$', views.register, name='register'),
	url(r'^createclient/$', views.createclient, name='createclient'),
	url(r'^createagence/$', views.createagence, name='createagence'),
	url(r'^createposte/$', views.createposte, name='createposte'),
	url(r'^createcaisse/$', views.createcaisse, name='createcaisse'),
	#url(r'^createcompte/$', views.createcompte, name='createcompte'),
	path('createcompte/<str:typecpt>/', views.createcompte, name='createcompte'),
	path('createversement/<str:cptecred>/<str:action>/', views.createversement, name='createversement'),
    url(r'^dashboard/$', views.dashboard, name='dashboard'),
	#url(r'^employeslist/$', views.employeslist, name='employeslist'),
	path('employeslist/<str:page>/', views.employeslist, name='employeslist'),
	path('employeslistfilter/', views.employeslistfilter, name='employeslistfilter'),
	path('posteslist/<str:page>/', views.posteslist, name='posteslist'),
	path('agenceslist/<str:page>/', views.agenceslist, name='agenceslist'),
	path('caisseslist/<str:page>/', views.caisseslist, name='caisseslist'),
	path('clientslist/<str:page>/', views.clientslist, name='clientslist'),
	path('compteslist/<str:page>/<str:tcpt>/', views.compteslist, name='compteslist'),
	path('pretslist/<str:page>/', views.pretslist, name='pretslist'),
	path('versementlist/<str:page>/<str:action>/', views.versementlist, name='versementlist'),
	path('historiques/<str:page>/', views.historiques, name='historiques'),
	
    url(r'^déconnexion/$', views.logout_user, name='logout'),
	url(r'^lock/$', views.lock_user, name='lock'),
    url(r'^media/(?P<path>.*)$', serve, { 'document_root': settings.MEDIA_ROOT}),
]

cooperative/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import url, include
from appbase import views
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
	url(r'^appbase/', include('appbase.urls')),
]


if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

appbase/forms.py
from django import forms

class RegisterForm(forms.Form):
	email =  forms.EmailField()
	username = forms.CharField(max_length=50)
	password1 = forms.CharField(max_length=50)
	password2 = forms.CharField(max_length=50)
	matricule = forms.CharField(max_length=50)
	nom = forms.CharField(max_length=100)
	prenom = forms.CharField(max_length=100)
	adresse = forms.CharField(max_length=30)
	tel = forms.CharField(max_length=500)
	profil = forms.CharField(max_length=1)
	poste = forms.CharField(max_length=1)
	photo = forms.ImageField()

class AgenceForm(forms.Form):
	code =  forms.CharField(max_length=50)
	societe =  forms.CharField(max_length=50)
	nom = forms.CharField(max_length=100)
	adresse = forms.CharField(max_length=50)
	tel = forms.CharField(max_length=50)

class CaisseForm(forms.Form):
	code =  forms.CharField(max_length=50)
	libelle =  forms.CharField(max_length=50)
	agence = forms.CharField(max_length=50)
	typecaisse = forms.CharField(max_length=1)

class PosteForm(forms.Form):
	code =  forms.CharField(max_length=50)
	libelle =  forms.CharField(max_length=50)
	agence = forms.CharField(max_length=50)
	service = forms.CharField(max_length=50)

class ClientForm(forms.Form):
	code =  forms.CharField(max_length=50)
	profession =  forms.CharField(max_length=50)
	nationalite = forms.CharField(max_length=50)
	cni = forms.CharField(max_length=50)
	datenaissance = forms.DateField()
	nom = forms.CharField(max_length=100)
	prenom = forms.CharField(max_length=100)
	adresse = forms.CharField(max_length=30)
	tel = forms.CharField(max_length=500)
	civilite = forms.CharField(max_length=1)
	photo = forms.ImageField()
	signatureclient = forms.ImageField()

class CompteFormClient(forms.Form):
	numero =  forms.CharField(max_length=50)
	typecompte =  forms.CharField(max_length=1)
	etat = forms.CharField(max_length=1)
	solde = forms.DecimalField(max_digits=20, decimal_places=2, localize=True)
	agence = forms.CharField(max_length=50)
	client = forms.CharField(max_length=50)
	epargne = forms.BooleanField(required=False)

class CompteFormBank(forms.Form):
	numero =  forms.CharField(max_length=50)
	typecompte =  forms.CharField(max_length=1)
	etat = forms.CharField(max_length=1)
	solde = forms.DecimalField(max_digits=20, decimal_places=2, localize=True)
	caisse = forms.CharField(max_length=50)
	agence = forms.CharField(max_length=50)
	epargne = forms.BooleanField(required=False)

class VersementForm(forms.Form):
	depositaire =  forms.CharField(max_length=100)
	montant = forms.DecimalField(max_digits=20, decimal_places=2, localize=True)
	motif = forms.CharField(max_length=250)
	compte = forms.CharField(max_length=50)
	cptecredit = forms.CharField(max_length=50)
	action = forms.CharField(max_length=1)

appbase/views.py
from django.shortcuts import get_object_or_404, render, redirect
from django.views import generic
from django.contrib.auth import authenticate, login
from django.contrib.auth import logout
from django.http import JsonResponse
from django.http import HttpResponse
from django.views.generic import TemplateView,ListView
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.views.generic.detail import DetailView
from django.urls import reverse_lazy
from django.urls import reverse
from django.http import HttpResponseRedirect
from django.forms import ModelForm
import json
import re
from django.db.models import Q
from django.contrib.auth.decorators import login_required
from django.template.loader import render_to_string
from django.http import JsonResponse
from . import models
from django.db import transaction
from .models import *
from django.contrib import messages
from django.conf import settings
import random
from django.core.mail import send_mail
import os
import time
import datetime
from django.core import serializers
from django.contrib.humanize.templatetags.humanize import naturaltime
from django.template.defaultfilters import filesizeformat
from .forms import RegisterForm, ClientForm, CompteFormClient, CompteFormBank, VersementForm, AgenceForm, CaisseForm, PosteForm
from django.db import IntegrityError
from django.core.paginator import Paginator
import traceback

def loginuser(request):
    if request.method == "POST":
        username = request.POST['username']
        password = request.POST['password']
        user = authenticate(username=username, password=password)
        if user is not None:
            if user.is_active:
                login(request, user)
                return redirect('appbase:dashboard')
            else:
                return render(request, 'appbase/pages/login.html', {'error_message': 'Votre compte a été désactivé', 'title': 'Connexion', 'color_msg': '#ffc107'})
        else:
            return render(request, 'appbase/login.html', {'error_message': 'Paramètres Invalides', 'title': 'Connexion', 'color_msg': '#dc3545'})
    return render(request, 'appbase/login.html', {'title': 'Connexion'})

def logout_user(request):
	logout(request)
	return redirect('appbase:login')

def lock_user(request):
	username = request.user.username
	logout(request)
	return render(request, 'appbase/lock.html', {'title': 'Connexion', 'username': username})

def register(request):
	employePost = Employe.objects.get(user_id=request.user.id)
	postes = Poste.objects.all()
	if request.method == "POST":
		MyRegisterForm = RegisterForm(request.POST, request.FILES)
		if MyRegisterForm.is_valid():
			try:
				username = MyRegisterForm.cleaned_data["username"]
				password = MyRegisterForm.cleaned_data["password1"]
				passwordConfirm = MyRegisterForm.cleaned_data["password2"]
				if password != passwordConfirm:
					return render(request, 'appbase/register.html', {'title': 'Création d\'un employé', 'postes': postes, 'message_confirm': 'Veuillez écrire le même mot de passe', 'color_msg': '#ffc107'})
				email = MyRegisterForm.cleaned_data["email"]
				user1 = User.objects.create_user(username, email, password)
			except IntegrityError:
				return render(request, 'appbase/register.html', {'title': 'Création d\'un employé', 'postes': postes, 'message_confirm': 'L\'utilisateur existe déjà', 'color_msg': '#dc3545'})
			try:
				employe = Employe()
				idposte = MyRegisterForm.cleaned_data["poste"]
				poste = Poste.objects.get(pk=idposte)
				employe.matricule = MyRegisterForm.cleaned_data["matricule"]
				employe.nom = MyRegisterForm.cleaned_data["nom"]
				employe.prenom = MyRegisterForm.cleaned_data["prenom"]
				employe.adresse = MyRegisterForm.cleaned_data["adresse"]
				employe.tel = MyRegisterForm.cleaned_data["tel"]
				employe.poste = poste
				employe.profil = MyRegisterForm.cleaned_data["profil"]
				employe.photo = MyRegisterForm.cleaned_data["photo"]
				employe.user = user1
				employe.save()
				return render(request, 'appbase/register.html', {'title': 'Création d\'un employé', 'postes': postes, 'message_confirm': 'Utilisateur créé avec succès', 'color_msg': '#28a745', 'employe': employePost})
			except IntegrityError:
				user1.delete()
				return render(request, 'appbase/register.html', {'title': 'Création d\'un employé', 'postes': postes, 'message_confirm': 'Un employé avec le ce numéro de matricule existe déjà', 'color_msg': '#dc3545', 'employe': employePost})
			except NameError:
				user1.delete()
				return render(request, 'appbase/register.html', {'title': 'Création d\'un employé', 'postes': postes, 'message_confirm': 'Le poste n\'existe plus', 'color_msg': '#dc3545', 'employe': employePost})
			except:
				user1.delete()
				return render(request, 'appbase/register.html', {'title': 'Création d\'un employé', 'postes': postes, 'message_confirm': 'Erreur de création', 'color_msg': '#dc3545', 'employe': employePost})
		else:
			return render(request, 'appbase/register.html', {'title': 'Création d\'un employé', 'postes': postes, 'message_confirm': 'Veuillez remplir tous les champs', 'color_msg': '#ffc107', 'employe': employePost})
	return render(request, 'appbase/register.html', {'title': 'Création d\'un employé', 'postes': postes, 'employe': employePost})

def dashboard(request):
	employe = Employe.objects.get(user_id=request.user.id)
	return render(request, 'appbase/dashboard.html', {'title': 'Tableau de bord', 'employe': employe, 'userid': request.user.id})

def employeslist(request, page):
	employe = Employe.objects.get(user_id=request.user.id)
	employes = Employe.objects.all()
	paginator = Paginator(employes, settings.DEFAULT_ITEMS_PER_PAGE)
	page_number = page
	if page_number is not None:
		page_obj = paginator.get_page(page_number)
		return render(request, 'appbase/employes.html', {'title': 'Liste des employés', 'employe': employe, 'userid': request.user.id, 'employes': page_obj})
	page_obj1 = paginator.get_page(1)
	return render(request, 'appbase/employes.html', {'title': 'Liste des employés', 'employe': employe, 'userid': request.user.id, 'employes': page_obj1})

def employeslistfilter(request):
	employe = Employe.objects.get(user_id=request.user.id)
	filterval = request.GET.get('searchitems')
	if filterval is not None:
		employes = Employe.objects.filter(Q(matricule=filterval) | Q(nom=filterval) | Q(prenom=filterval) | Q(adresse=filterval))
		paginator = Paginator(employes, settings.DEFAULT_ITEMS_PER_PAGE)
		page_obj = paginator.get_page(1)
		return render(request, 'appbase/employes.html', {'title': 'Liste des employés', 'employe': employe, 'userid': request.user.id, 'employes': page_obj})
	#employeslist(request, 1)

def clientslist(request, page):
	employe = Employe.objects.get(user_id=request.user.id)
	clients = Client.objects.all()
	paginator = Paginator(clients, settings.DEFAULT_ITEMS_PER_PAGE)
	page_number = page
	if page_number is not None:
		page_obj = paginator.get_page(page_number)
		return render(request, 'appbase/clients.html', {'title': 'Liste des clients', 'employe': employe, 'clients': page_obj})
	page_obj1 = paginator.get_page(1)
	return render(request, 'appbase/clients.html', {'title': 'Liste des clients', 'employe': employe, 'clients': page_obj1})

def createclient(request):
	employePost = Employe.objects.get(user_id=request.user.id)
	if request.method == "POST":
		MyClientForm = ClientForm(request.POST, request.FILES)
		if MyClientForm.is_valid():
			try:
				client = Client()
				client.code = MyClientForm.cleaned_data["code"]
				client.nom = MyClientForm.cleaned_data["nom"]
				client.prenom = MyClientForm.cleaned_data["prenom"]
				client.adresse = MyClientForm.cleaned_data["adresse"]
				client.tel = MyClientForm.cleaned_data["tel"]
				client.cni = MyClientForm.cleaned_data["cni"]
				client.civilite = MyClientForm.cleaned_data["civilite"]
				client.photo = MyClientForm.cleaned_data["photo"]
				client.signature = MyClientForm.cleaned_data["signatureclient"]
				client.nationalite = MyClientForm.cleaned_data["nationalite"]
				client.datenaissance = MyClientForm.cleaned_data["datenaissance"]
				client.profession = MyClientForm.cleaned_data["datenaissance"]
				client.save()
				return render(request, 'appbase/createclient.html', {'title': 'Création d\'un client', 'message_confirm': 'Client créé avec succès', 'color_msg': '#28a745', 'employe': employePost})
			except IntegrityError:
				return render(request, 'appbase/createclient.html', {'title': 'Création d\'un client', 'message_confirm': 'Un client avec le ce numéro de matricule existe déjà', 'color_msg': '#dc3545', 'employe': employePost})
			except NameError:
				return render(request, 'appbase/createclient.html', {'title': 'Création d\'un client', 'message_confirm': 'Le client n\'existe plus', 'color_msg': '#dc3545', 'employe': employePost})
			except:
				return render(request, 'appbase/createclient.html', {'title': 'Création d\'un client', 'message_confirm': 'Erreur de création', 'color_msg': '#dc3545', 'employe': employePost})
		else:
			return render(request, 'appbase/createclient.html', {'title': 'Création d\'un client', 'message_confirm': 'Veuillez remplir tous les champs', 'color_msg': '#ffc107', 'employe': employePost})
	return render(request, 'appbase/createclient.html', {'title': 'Création d\'un client', 'employe': employePost})

def createagence(request):
	employePost = Employe.objects.get(user_id=request.user.id)
	if request.method == "POST":
		MyAgenceForm = AgenceForm(request.POST, request.FILES)
		if MyAgenceForm.is_valid():
			try:
				agence = Agence()
				agence.code = MyAgenceForm.cleaned_data["code"]
				agence.societe = MyAgenceForm.cleaned_data["societe"]
				agence.nom = MyAgenceForm.cleaned_data["nom"]
				agence.adresse = MyAgenceForm.cleaned_data["adresse"]
				agence.tel = MyAgenceForm.cleaned_data["tel"]
				agence.save()

appbase/templates/appbase/filters/employes.html
{% extends "baseTemplate.html" %}
{% load static %}
{% block title %}
{{ title }}
{% endblock %}
{% block styles %} 
{% endblock %}
{% block content %}

<div class="main-content-inner">
	<div class="row">
		<!-- table primary start -->
		<div class="col-lg-12 mt-5">
			<div class="card">
				
				<div class="card-body">
					<div class="table-title">
						<div class="row">
							<div class="col-sm-4">
								<h4 style="margin-top: 15px;">
									<b>{{ title }}</b>
								</h4>
							</div>
							<div style="margin-top: 18px;" class="col-sm-3">
									<form action="#">
										<input type="text" name="searchitems" placeholder="Filtrer..." required="">
									</form>
							</div>
							<div class="col-sm-5">
								<a href="{% url 'appbase:register' %}" class="btn btn-primary" style="float: right;">Créer un employé<i class="fa fa-plus-circle" aria-hidden="true" style="margin-left: 5px;"></i></a>
							</div>
						</div>
					</div>
					
					<div class="single-table">
						<div class="table-responsive">
							<table class="table text-center" style="font-family: 'Poppins', sans-serif;text-transform: capitalize;">
								<thead class="text-uppercase bg-primary">
									<tr class="text-white">
										<th scope="col">ID</th>
										<th scope="col">Photo</th>
										<th scope="col">Matricule</th>
										<th scope="col">Nom</th>
										<th scope="col">Prenom</th>
										<th scope="col">Profil</th>
										<th scope="col" colspan=2>Actions</th>
										<th scope="col">Mandataires</th>
									</tr>
								</thead>
								<tbody>
									{% for empl in employes %}
										<tr style="border-right: 2px solid lightgray;border-bottom: 1px solid lightgray;">
											<th scope="row" style="vertical-align: middle;border-right: 1px solid lightgray;border-left: 1px solid lightgray;">{{ forloop.counter }}</th>
											<td style="vertical-align: middle;border-right: 1px solid lightgray;">
												{% if empl.photo.url %}
												<img class="avatar user-thumb" src="{{ empl.photo.url }}" style="height: 30%;">
												{% else %}
												<img class="avatar user-thumb" src="{% static 'appbase/images/author/avatar.png' %}" alt="avatar" style="height: 30%;">
												{% endif %}
											</td>
											<td style="vertical-align: middle;border-right: 1px solid lightgray;">{{ empl.matricule }}</td>
											<td style="vertical-align: middle;border-right: 1px solid lightgray;">{{ empl.nom }}</td>
											<td style="vertical-align: middle;border-right: 1px solid lightgray;">{{ empl.prenom }}</td>
											<td style="vertical-align: middle;border-right: 1px solid lightgray;">
												{% if empl.profil == "A" %}
													Administrateur
												{% elif empl.profil == "C" %}
													Caissier
												{% elif empl.profil == "D" %}
													Chef d'agence
												{% else %}
													-
												{% endif %}
											</td>
											
											<td style="vertical-align: middle;border-right: 1px solid lightgray;"><a href="#" class="text-info"><i class="fa fa-edit"></i></a></td>
											<td style="vertical-align: middle;border-right: 1px solid lightgray;"><a href="#" class="text-danger"><i class="ti-trash"></i></a></td>
											<td style="vertical-align: middle;border-left: 1px solid lightgray;"><a href="#" class="text-info"><i class="fa fa-users"></i></a></td>
										</tr>
									{% endfor %}
								</tbody>
							</table>
							<div>
							<div style="margin-top: 18px;float: left;">
								Page {{ employes.number }} sur {{ employes.paginator.num_pages }}.
							</div>
                            <div style="margin-top: 10px;float: right;border: 1px solid #007BFF;border-radius: 3%;">
								
                                <nav aria-label="...">
                                    <ul class="pagination pg-color-border">
											{% if employes.has_previous %}
												<li class="page-item">
													<a class="page-link" href="{% url 'appbase:employeslist' page=1 %}">1</a>
												</li>
												{% if employes.previous_page_number != 1 %}
													<li class="page-item">
														<a class="page-link" href="{% url 'appbase:employeslist' page=employes.previous_page_number  %}">Précedent</a>
													</li>
												{% endif %}
											{% endif %}
												<span style="background-color: #007bff;">
													<li class="page-item" active>
														<a class="page-link" href="{% url 'appbase:employeslist' page=employes.number  %}">{{employes.number}}</a>
													</li>
												</span>
											{% if employes.has_next  %}
												{% if employes.next_page_number != employes.paginator.num_pages %}
													<li class="page-item">
														<a class="page-link" href="{% url 'appbase:employeslist' page=employes.next_page_number %}">Suivant</a>
													</li>
												{% endif %}
												<li class="page-item">
													<a class="page-link" href="{% url 'appbase:employeslist' page=employes.paginator.num_pages %}">Fin &raquo;</a>
												</li>
											{% endif %}
                                    </ul>
                                </nav>
                            </div>
							</div>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
</div>
{% endblock %}